version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 0
    labels:
      - dependencies
  - package-ecosystem: pip
    directory: "/manager"
    schedule:
      interval: monthly
    open-pull-requests-limit: 0
    labels:
      - dependencies

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 0
    labels:
      - dependencies
