from __future__ import annotations

import json
import subprocess
import sys
import uuid
from pathlib import Path

import yaml


ROOT = Path(__file__).resolve().parents[1]
CLI = ROOT / "atom-learn" / "scripts" / "atomlearn.py"
CALCULUS_PLAN = ROOT / "examples" / "calculus-mini" / "plan.yaml"
OS_PLAN = ROOT / "examples" / "operating-systems-mini" / "plan.yaml"
RUN_ROOT = ROOT / ".test-workspaces"


def invoke(*args: object, check: bool = True) -> subprocess.CompletedProcess[str]:
    result = subprocess.run(
        [sys.executable, str(CLI), *(str(arg) for arg in args)],
        cwd=ROOT,
        text=True,
        encoding="utf-8",
        capture_output=True,
        check=False,
    )
    if check and result.returncode != 0:
        raise AssertionError(f"command failed: {result.args}\nstdout={result.stdout}\nstderr={result.stderr}")
    return result


def output_json(result: subprocess.CompletedProcess[str]) -> dict:
    return json.loads(result.stdout)


def new_workspace(label: str, plan: Path = CALCULUS_PLAN) -> tuple[Path, int]:
    RUN_ROOT.mkdir(parents=True, exist_ok=True)
    workspace = RUN_ROOT / f"{label}-{uuid.uuid4().hex}"
    output_json(
        invoke(
            "init",
            workspace,
            "--course-id",
            f"test.{label}",
            "--title",
            f"Test {label}",
            "--goal",
            "Exercise AtomLearn deterministically",
        )
    )
    imported = output_json(invoke("import-plan", workspace, "--input", plan, "--expected-revision", 0))
    return workspace, imported["revision"]


def write_payload(workspace: Path, name: str, payload: dict) -> Path:
    path = workspace / name
    path.write_text(yaml.safe_dump(payload, allow_unicode=True, sort_keys=False), encoding="utf-8")
    return path


def status(workspace: Path) -> dict:
    return output_json(invoke("status", workspace, "--json"))


def activate(workspace: Path, atom_id: str, revision: int) -> int:
    return output_json(
        invoke("activate", workspace, atom_id, "--expected-revision", revision)
    )["revision"]


def evidence_payload(atom_id: str, score: float, kind: str = "mastery_check") -> dict:
    return {
        "atom_id": atom_id,
        "kind": kind,
        "prompt": "Explain and apply the current idea, then address its main misconception.",
        "response_summary": "The learner produced a concise explanation and a worked response.",
        "scores": {"explain": score, "apply": score, "discriminate": score},
        "feedback": "The response was evaluated against the declared dimensions.",
        "rationale": "The score records observable performance rather than self-reported confidence.",
    }


def assess_once(
    workspace: Path,
    atom_id: str,
    revision: int,
    score: float,
    *,
    kind: str = "mastery_check",
    now: str = "2026-01-01T00:00:00+00:00",
) -> tuple[int, str]:
    payload = write_payload(workspace, f"evidence-{uuid.uuid4().hex}.yaml", evidence_payload(atom_id, score, kind))
    recorded = output_json(
        invoke("record-evidence", workspace, "--input", payload, "--expected-revision", revision)
    )
    assessed = output_json(
        invoke(
            "assess",
            workspace,
            atom_id,
            "--evidence-id",
            recorded["evidence_id"],
            "--now",
            now,
            "--expected-revision",
            recorded["revision"],
        )
    )
    return assessed["revision"], assessed["result"]


def test_init_import_validate_render_and_status() -> None:
    workspace, revision = new_workspace("orientation")
    validated = output_json(invoke("validate", workspace))
    assert validated == {"ok": True, "revision": revision, "atoms": 5}

    state = status(workspace)
    assert state["session"]["active_atom_id"] is None
    assert state["counts"] == {"available": 2, "locked": 3}
    assert {item["id"] for item in state["next_candidates"]} == {
        "calculus.limit.approach",
        "calculus.rate.average",
    }
    for filename in ["LEARNING_MAP.md", "CURRENT.md", "PROGRESS.md", "QUESTIONS.md", "SOURCES.md"]:
        text = (workspace / filename).read_text(encoding="utf-8")
        assert "Generated by AtomLearn" in text


def test_mastery_requires_evidence_and_unlocks_successors() -> None:
    workspace, revision = new_workspace("mastery")
    revision = activate(workspace, "calculus.limit.approach", revision)

    revision, result = assess_once(workspace, "calculus.limit.approach", revision, 0.55)
    assert result == "partial"
    state = status(workspace)
    assert state["active_atom"]["id"] == "calculus.limit.approach"
    assert state["session"]["next_action"].startswith("Remediate")

    revision, result = assess_once(workspace, "calculus.limit.approach", revision, 0.9)
    assert result == "mastered"
    state = status(workspace)
    assert state["session"]["active_atom_id"] is None
    assert state["counts"]["mastered"] == 1
    assert len(yaml.safe_load((workspace / ".atomlearn" / "reviews.yaml").read_text(encoding="utf-8"))["items"]) == 1

    stale = invoke(
        "activate",
        workspace,
        "calculus.rate.average",
        "--expected-revision",
        revision - 1,
        check=False,
    )
    assert stale.returncode == 2
    assert "Stale revision" in stale.stderr


def test_future_question_is_parked_without_changing_focus() -> None:
    workspace, revision = new_workspace("questions", OS_PLAN)
    revision = activate(workspace, "os.program.definition", revision)
    payload = write_payload(
        workspace,
        "question.yaml",
        {
            "text": "那线程是什么？",
            "classification": "future_atom",
            "related_atom_id": "os.thread.definition",
            "rationale": "Threads have their own mapped Atom after process context.",
            "priority": "normal",
        },
    )
    recorded = output_json(
        invoke("record-question", workspace, "--input", payload, "--expected-revision", revision)
    )
    state = status(workspace)
    assert state["session"]["active_atom_id"] == "os.program.definition"
    assert state["session"]["phase"] == "teaching"
    question = next(item for item in state["open_questions"] if item["id"] == recorded["question_id"])
    assert question["status"] == "parked"
    assert question["related_atom_id"] == "os.thread.definition"


def test_evidence_can_be_recorded_only_for_the_active_atom() -> None:
    workspace, revision = new_workspace("evidence-guard")
    available_payload = write_payload(
        workspace,
        "available-evidence.yaml",
        evidence_payload("calculus.limit.approach", 0.9),
    )
    without_active = invoke(
        "record-evidence",
        workspace,
        "--input",
        available_payload,
        "--expected-revision",
        revision,
        check=False,
    )
    assert without_active.returncode == 2
    assert "only for the Active Atom" in without_active.stderr

    revision = activate(workspace, "calculus.limit.approach", revision)
    locked_payload = write_payload(
        workspace,
        "locked-evidence.yaml",
        evidence_payload("calculus.derivative.definition", 0.9),
    )
    for_locked = invoke(
        "record-evidence",
        workspace,
        "--input",
        locked_payload,
        "--expected-revision",
        revision,
        check=False,
    )
    assert for_locked.returncode == 2
    assert "requested 'calculus.derivative.definition'" in for_locked.stderr
    assert status(workspace)["course"]["revision"] == revision
    evidence = yaml.safe_load(
        (workspace / ".atomlearn" / "evidence.yaml").read_text(encoding="utf-8")
    )
    assert evidence["items"] == []
    assert output_json(invoke("validate", workspace))["ok"] is True


def test_due_review_can_be_activated() -> None:
    workspace, revision = new_workspace("review")
    revision = activate(workspace, "calculus.limit.approach", revision)
    revision, result = assess_once(workspace, "calculus.limit.approach", revision, 0.9)
    assert result == "mastered"
    refreshed = output_json(
        invoke(
            "refresh-reviews",
            workspace,
            "--now",
            "2026-01-03T00:00:00+00:00",
            "--expected-revision",
            revision,
        )
    )
    assert refreshed["due_atom_ids"] == ["calculus.limit.approach"]
    revision = activate(workspace, "calculus.limit.approach", refreshed["revision"])
    state = status(workspace)
    assert state["session"]["phase"] == "reviewing"
    assert state["active_atom"]["status"] == "active"
    assert revision == refreshed["revision"] + 1

    blocked = invoke(
        "skip",
        workspace,
        "calculus.limit.approach",
        "--mode",
        "defer",
        "--reason-code",
        "time_constraint",
        "--expected-revision",
        revision,
        check=False,
    )
    assert blocked.returncode == 2
    assert "already has mastered Evidence" in blocked.stderr
    assert status(workspace)["course"]["revision"] == revision


def test_invalid_cycle_is_rejected_without_persisting() -> None:
    workspace, revision = new_workspace("cycle")
    cycle_plan = write_payload(
        workspace,
        "cycle.yaml",
        {
            "atoms": [
                {
                    "id": "cycle.a",
                    "title": "Cycle A",
                    "objective": "Explain A",
                    "prerequisites": ["cycle.b"],
                },
                {
                    "id": "cycle.b",
                    "title": "Cycle B",
                    "objective": "Explain B",
                    "prerequisites": ["cycle.a"],
                },
            ]
        },
    )
    rejected = invoke(
        "import-plan",
        workspace,
        "--input",
        cycle_plan,
        "--expected-revision",
        revision,
        check=False,
    )
    assert rejected.returncode == 2
    assert "contains a cycle" in rejected.stderr
    assert status(workspace)["course"]["revision"] == revision
    assert output_json(invoke("validate", workspace))["ok"] is True


def test_blocking_backtrack_returns_to_parent() -> None:
    workspace, revision = new_workspace("backtrack")
    revision = activate(workspace, "calculus.limit.approach", revision)
    revision, result = assess_once(workspace, "calculus.limit.approach", revision, 0.9)
    assert result == "mastered"
    revision = activate(workspace, "calculus.rate.average", revision)
    question_payload = write_payload(
        workspace,
        "blocking.yaml",
        {
            "text": "趋近和等于的区别会不会影响这里？",
            "classification": "blocking_prerequisite",
            "related_atom_id": "calculus.limit.approach",
            "rationale": "The learner needs to revisit the distinction before continuing.",
            "priority": "high",
        },
    )
    question = output_json(
        invoke("record-question", workspace, "--input", question_payload, "--expected-revision", revision)
    )
    backtracked = output_json(
        invoke(
            "backtrack",
            workspace,
            "--to",
            "calculus.limit.approach",
            "--question-id",
            question["question_id"],
            "--expected-revision",
            question["revision"],
        )
    )
    assert backtracked["active_atom_id"] == "calculus.limit.approach"
    revision, result = assess_once(
        workspace,
        "calculus.limit.approach",
        backtracked["revision"],
        0.9,
        kind="review",
    )
    assert result == "mastered"
    resumed = output_json(invoke("resume", workspace, "--expected-revision", revision))
    assert resumed["active_atom_id"] == "calculus.rate.average"
    state = status(workspace)
    assert state["session"]["backtrack_stack"] == []
    assert state["session"]["phase"] == "questioning"


def test_restructure_requires_confirmation_and_preserves_alias() -> None:
    workspace, revision = new_workspace("restructure")
    proposal = write_payload(
        workspace,
        "split.yaml",
        {
            "action": "split",
            "source_atom_id": "calculus.limit.approach",
            "downstream_replacement_id": "calculus.limit.distinguish",
            "new_atoms": [
                {
                    "id": "calculus.limit.sequence-intuition",
                    "title": "序列趋近的直觉",
                    "module": "Limits",
                    "objective": "解释序列逐步逼近一个值",
                    "prerequisites": [],
                    "mastery": {
                        "required_dimensions": ["explain"],
                        "pass_threshold": 0.8,
                        "minimum_dimension_score": 0.6,
                    },
                },
                {
                    "id": "calculus.limit.distinguish",
                    "title": "趋近与取到的辨析",
                    "module": "Limits",
                    "objective": "辨析趋近与实际取值",
                    "prerequisites": ["calculus.limit.sequence-intuition"],
                    "mastery": {
                        "required_dimensions": ["explain", "discriminate"],
                        "pass_threshold": 0.8,
                        "minimum_dimension_score": 0.6,
                    },
                },
            ],
        },
    )
    preview = output_json(
        invoke("restructure", workspace, "--proposal", proposal, "--expected-revision", revision)
    )
    assert preview["applied"] is False
    assert status(workspace)["course"]["revision"] == revision

    applied = output_json(
        invoke(
            "restructure",
            workspace,
            "--proposal",
            proposal,
            "--confirmed",
            "--expected-revision",
            revision,
        )
    )
    assert applied["applied"] is True
    graph = yaml.safe_load((workspace / ".atomlearn" / "graph.yaml").read_text(encoding="utf-8"))
    assert graph["aliases"]["calculus.limit.approach"] == "calculus.limit.distinguish"
    archived = yaml.safe_load(
        (workspace / ".atomlearn" / "atoms" / "calculus.limit.approach.yaml").read_text(encoding="utf-8")
    )
    assert archived["status"] == "archived"
    assert output_json(invoke("validate", workspace))["ok"] is True


def test_single_atom_course_completes_and_revision_mismatch_is_detected() -> None:
    RUN_ROOT.mkdir(parents=True, exist_ok=True)
    workspace = RUN_ROOT / f"completion-{uuid.uuid4().hex}"
    output_json(
        invoke(
            "init",
            workspace,
            "--course-id",
            "test.completion",
            "--title",
            "One Atom",
            "--goal",
            "Finish one observable objective",
        )
    )
    plan = write_payload(
        workspace,
        "plan.yaml",
        {
            "atoms": [
                {
                    "id": "one.atom",
                    "title": "One Atom",
                    "objective": "Explain and apply one idea",
                    "prerequisites": [],
                    "mastery": {
                        "required_dimensions": ["explain", "apply"],
                        "pass_threshold": 0.8,
                        "minimum_dimension_score": 0.6,
                    },
                }
            ]
        },
    )
    revision = output_json(
        invoke("import-plan", workspace, "--input", plan, "--expected-revision", 0)
    )["revision"]
    revision = activate(workspace, "one.atom", revision)
    revision, result = assess_once(workspace, "one.atom", revision, 0.9)
    assert result == "mastered"
    assert status(workspace)["course"]["status"] == "completed"

    current_path = workspace / ".atomlearn" / "state" / "current.yaml"
    current = yaml.safe_load(current_path.read_text(encoding="utf-8"))
    current["revision"] = revision + 1
    current_path.write_text(yaml.safe_dump(current, sort_keys=False), encoding="utf-8")
    invalid = invoke("validate", workspace, check=False)
    assert invalid.returncode == 2
    assert "does not match course.revision" in invalid.stderr
