#!/usr/bin/env python3
"""Bounded, evidence-driven evolution engine for AtomLearn."""

from __future__ import annotations

import argparse
import copy
import hashlib
import json
import re
import sys
from collections import defaultdict
from pathlib import Path
from typing import Any

import yaml

from platform_state import PlatformStateError

from atomlearn import (
    SCHEMA_VERSION,
    AtomLearnError,
    Workspace,
    atomic_text,
    iso,
    load_workspace,
    now_utc,
    read_data,
    require_id,
    require_number,
    require_string,
    unique,
    write_yaml,
)


EVOLUTION_TYPES = {
    "teaching_strategy",
    "adjust_review_intervals",
    "adjust_mastery",
    "add_dependency",
    "remove_dependency",
    "split_atom",
    "merge_atoms",
    "patch_skill",
}
TYPE_RISK = {
    "teaching_strategy": "low",
    "adjust_review_intervals": "low",
    "adjust_mastery": "medium",
    "add_dependency": "medium",
    "remove_dependency": "medium",
    "split_atom": "medium",
    "merge_atoms": "medium",
    "patch_skill": "high",
}
PROPOSAL_STATUSES = {
    "proposed",
    "approved",
    "applied",
    "monitoring",
    "promoted",
    "rejected",
    "rolled_back",
    "blocked",
}
AUTHORITY_RANK = {"learner": 1, "maintainer": 2}
RISK_AUTHORITY = {"low": "learner", "medium": "learner", "high": "maintainer"}
COURSE_MUTATION_TYPES = {
    "adjust_review_intervals",
    "adjust_mastery",
    "add_dependency",
    "remove_dependency",
    "split_atom",
    "merge_atoms",
}
PROPOSAL_ID_PATTERN = re.compile(r"evo-\d{6,}")
SUPPORTED_METRICS = {
    "atom.average_score",
    "atom.attempts",
    "atom.evidence_count",
    "atom.mastery_failures",
    "atom.review_failures",
    "atom.dimension_spread",
    "atom.blocking_questions_as_current",
    "atom.parked_questions",
    "course.mastered_ratio",
    "course.skipped_atoms",
    "course.skipped_ratio",
    "course.deferred_atoms",
    "course.open_questions",
    "course.parked_questions",
    "course.pending_reviews",
    "course.total_evidence",
    "system.workspace_validation_errors",
    "system.active_atom_count",
    "system.mastered_without_evidence",
}
SUPPORTED_OPERATORS = {"gte", "lte", "gt", "lt", "eq"}
REQUIRED_INVARIANTS = {
    "exactly_one_active_atom",
    "prerequisites_before_activation",
    "mastery_requires_evidence",
    "preserve_sources",
    "preserve_history",
    "no_runtime_skill_patch",
}


class EvolutionError(RuntimeError):
    """A user-correctable evolution error."""


def template_dir() -> Path:
    from core_paths import CORE_ROOT

    return CORE_ROOT / "assets" / "templates"


def initialize_evolution(root: Path) -> None:
    root = root.resolve()
    meta = root / ".atomlearn"
    if not meta.is_dir():
        raise EvolutionError(f"Not an AtomLearn workspace: {root}")
    evolution = meta / "evolution"
    for directory in ["proposals", "experiments", "checkpoints"]:
        (evolution / directory).mkdir(parents=True, exist_ok=True)
    mapping = {
        "policy.yaml": "evolution-policy.yaml",
        "state.yaml": "evolution-state.yaml",
        "metrics.yaml": "evolution-metrics.yaml",
        "hypotheses.yaml": "evolution-hypotheses.yaml",
    }
    for destination, source in mapping.items():
        path = evolution / destination
        if path.exists():
            continue
        data = read_data(template_dir() / source)
        if destination == "state.yaml":
            data["updated_at"] = iso()
        write_yaml(path, data)
    ledger = evolution / "ledger.ndjson"
    if not ledger.exists():
        atomic_text(ledger, "")
    view = root / "EVOLUTION.md"
    if not view.exists():
        atomic_text(
            view,
            "# Evolution State\n\n"
            "> Generated by AtomLearn Evolution Engine. Use `atomlearn evolve` commands to change state.\n\n"
            "## Policy\n\n- Mode: `proposal_only`\n- Evolution revision: 0\n\n"
            "## Open Hypotheses\n\n- None\n\n## Proposals\n\n- None\n",
        )


def proposal_sequence(paths: list[Path]) -> int:
    maximum = 0
    for path in paths:
        stem = path.stem
        if stem.startswith("evo-") and stem[4:].isdigit():
            maximum = max(maximum, int(stem[4:]))
    return maximum + 1


def safe_mean(values: list[float]) -> float | None:
    return round(sum(values) / len(values), 3) if values else None


def stable_fingerprint(kind: str, targets: list[str], observations: list[str]) -> str:
    content = json.dumps(
        {"kind": kind, "targets": sorted(targets), "observations": sorted(observations)},
        sort_keys=True,
        separators=(",", ":"),
    )
    return hashlib.sha256(content.encode("utf-8")).hexdigest()[:16]


class EvolutionEngine:
    def __init__(self, workspace: Workspace):
        self.workspace = workspace
        self.root = workspace.root / ".atomlearn" / "evolution"
        initialize_evolution(workspace.root)
        self.policy = read_data(self.root / "policy.yaml")
        self.state = read_data(self.root / "state.yaml")
        self.metrics = read_data(self.root / "metrics.yaml")
        self.hypotheses = read_data(self.root / "hypotheses.yaml")

    @classmethod
    def load(cls, workspace_path: str) -> "EvolutionEngine":
        workspace = load_workspace(workspace_path)
        errors = workspace.validate()
        if errors:
            raise EvolutionError("Cannot evolve an invalid workspace:\n- " + "\n- ".join(errors))
        return cls(workspace)

    @property
    def revision(self) -> int:
        value = self.state.get("revision")
        if not isinstance(value, int) or value < 0:
            raise EvolutionError("evolution state revision must be a non-negative integer")
        return value

    def expect_revision(self, expected: int | None) -> None:
        if expected is not None and expected != self.revision:
            raise EvolutionError(
                f"Stale evolution revision: expected {expected}, current is {self.revision}. Reload evolution status."
            )

    def proposal_paths(self) -> list[Path]:
        return sorted((self.root / "proposals").glob("evo-*.yaml"))

    def adaptation_summary(self) -> dict[str, Any]:
        root = self.workspace.meta / "adaptation"
        state_path = root / "state.yaml"
        profile_path = root / "profile.yaml"
        if not state_path.is_file() or not profile_path.is_file():
            return {
                "enabled": False,
                "adaptation_revision": None,
                "session_count": 0,
                "active_preferences": {},
                "pending_preferences": 0,
            }
        from adaptation import AdaptationEngine

        engine = AdaptationEngine.load(str(self.workspace.root))
        errors = engine.validate()
        if errors:
            raise EvolutionError("Session adaptation validation failed:\n- " + "\n- ".join(errors))
        state = engine.state
        profile = engine.profile
        preferences = profile.get("preferences", {})
        active = {
            dimension: item.get("active_value")
            for dimension, item in preferences.items()
            if isinstance(item, dict) and item.get("status") == "active" and item.get("active_value")
        }
        return {
            "enabled": True,
            "adaptation_revision": state.get("revision"),
            "session_count": state.get("session_count", 0),
            "active_preferences": active,
            "pending_preferences": sum(
                isinstance(item, dict) and item.get("status") in {"provisional", "contested"}
                for item in preferences.values()
            ),
        }

    def proposals(self) -> list[dict[str, Any]]:
        return [read_data(path) for path in self.proposal_paths()]

    def find_proposal(self, proposal_id: str) -> dict[str, Any]:
        if not isinstance(proposal_id, str) or not PROPOSAL_ID_PATTERN.fullmatch(proposal_id):
            raise EvolutionError(f"Invalid evolution proposal ID: {proposal_id!r}")
        path = self.root / "proposals" / f"{proposal_id}.yaml"
        if not path.is_file():
            raise EvolutionError(f"Evolution proposal not found: {proposal_id}")
        return read_data(path)

    def save_proposal(self, proposal: dict[str, Any]) -> None:
        proposal["evolution_revision"] = self.revision + 1
        proposal["updated_at"] = iso()
        write_yaml(self.root / "proposals" / f"{proposal['id']}.yaml", proposal)

    def commit(self, event_type: str, details: dict[str, Any] | None = None) -> None:
        new_revision = self.revision + 1
        self.state["revision"] = new_revision
        self.state["updated_at"] = iso()
        self.policy["revision"] = new_revision
        self.metrics["evolution_revision"] = new_revision
        self.hypotheses["evolution_revision"] = new_revision
        write_yaml(self.root / "policy.yaml", self.policy)
        write_yaml(self.root / "metrics.yaml", self.metrics)
        write_yaml(self.root / "hypotheses.yaml", self.hypotheses)
        write_yaml(self.root / "state.yaml", self.state)
        event = {
            "event_id": f"eevt-{new_revision:06d}",
            "revision": new_revision,
            "type": event_type,
            "at": self.state["updated_at"],
            "course_revision": self.workspace.revision,
            "details": details or {},
        }
        with (self.root / "ledger.ndjson").open("a", encoding="utf-8", newline="\n") as handle:
            handle.write(json.dumps(event, ensure_ascii=False, separators=(",", ":")) + "\n")
            handle.flush()
        self.render()

    def validate(self) -> list[str]:
        errors: list[str] = []
        for label, record in [
            ("policy", self.policy),
            ("state", self.state),
            ("metrics", self.metrics),
            ("hypotheses", self.hypotheses),
        ]:
            if record.get("schema_version") != SCHEMA_VERSION:
                errors.append(f"evolution {label}: unsupported schema_version")
        if self.policy.get("revision") != self.revision:
            errors.append("evolution policy revision does not match state revision")
        if self.metrics.get("evolution_revision") != self.revision:
            errors.append("evolution metrics revision does not match state revision")
        if self.hypotheses.get("evolution_revision") != self.revision:
            errors.append("evolution hypotheses revision does not match state revision")
        if self.policy.get("mode") != "proposal_only":
            errors.append("evolution policy mode must remain proposal_only in this release")
        if self.policy.get("privacy", {}).get("store_raw_messages") is not False:
            errors.append("evolution privacy.store_raw_messages must remain false")
        if self.policy.get("privacy", {}).get("cross_workspace_aggregation") is not False:
            errors.append("cross-workspace aggregation is not supported in this release")
        if self.policy.get("auto_apply_types") != []:
            errors.append("auto_apply_types must remain empty in proposal-only mode")
        permissions = self.policy.get("risk_permissions", {})
        for risk, required in RISK_AUTHORITY.items():
            configured = permissions.get(risk)
            if configured not in AUTHORITY_RANK or AUTHORITY_RANK[configured] < AUTHORITY_RANK[required]:
                errors.append(f"risk permission {risk} cannot be lower than {required}")
        invariants = self.policy.get("protected_invariants", [])
        missing_invariants = sorted(REQUIRED_INVARIANTS - set(invariants if isinstance(invariants, list) else []))
        if missing_invariants:
            errors.append("missing protected invariants: " + ", ".join(missing_invariants))
        ids: set[str] = set()
        for proposal in self.proposals():
            proposal_id = proposal.get("id")
            if not isinstance(proposal_id, str) or proposal_id in ids:
                errors.append(f"invalid or duplicate evolution proposal ID: {proposal_id!r}")
            ids.add(str(proposal_id))
            if proposal.get("type") not in EVOLUTION_TYPES:
                errors.append(f"{proposal_id}: invalid evolution type")
            if proposal.get("risk") != TYPE_RISK.get(proposal.get("type")):
                errors.append(f"{proposal_id}: risk does not match protected type risk")
            if proposal.get("status") not in PROPOSAL_STATUSES:
                errors.append(f"{proposal_id}: invalid status")
            if proposal.get("type") == "patch_skill" and proposal.get("status") in {
                "applied",
                "monitoring",
                "promoted",
            }:
                errors.append(f"{proposal_id}: runtime Skill patches are forbidden")
        return unique(errors)

    def compute_metrics(self) -> dict[str, Any]:
        questions = self.workspace.questions.get("items", [])
        evidence = self.workspace.evidence.get("items", [])
        reviews = self.workspace.reviews.get("items", [])
        atoms: dict[str, Any] = {}
        for atom_id, atom in self.workspace.atoms.items():
            atom_evidence = [item for item in evidence if item.get("atom_id") == atom_id]
            atom_questions = [
                item
                for item in questions
                if item.get("active_atom_id_at_creation") == atom_id or item.get("related_atom_id") == atom_id
            ]
            dimension_values: dict[str, list[float]] = defaultdict(list)
            for item in atom_evidence:
                for dimension, score in item.get("scores", {}).items():
                    if isinstance(score, (int, float)) and not isinstance(score, bool):
                        dimension_values[str(dimension)].append(float(score))
            dimension_averages = {
                dimension: safe_mean(values) for dimension, values in sorted(dimension_values.items())
            }
            average_values = [value for value in dimension_averages.values() if value is not None]
            atoms[atom_id] = {
                "title": atom.get("title"),
                "status": atom.get("status"),
                "attempts": int(atom.get("attempts", 0)),
                "evidence_count": len(atom_evidence),
                "assessed_evidence_count": sum(item.get("result") != "pending" for item in atom_evidence),
                "mastery_failures": sum(item.get("result") in {"partial", "not_mastered"} for item in atom_evidence),
                "review_failures": sum(
                    item.get("kind") == "review" and item.get("result") in {"partial", "not_mastered"}
                    for item in atom_evidence
                ),
                "average_score": safe_mean(
                    [float(score) for item in atom_evidence for score in item.get("scores", {}).values()]
                ),
                "dimension_averages": dimension_averages,
                "dimension_spread": round(max(average_values) - min(average_values), 3)
                if len(average_values) >= 2
                else 0.0,
                "blocking_questions_as_current": sum(
                    item.get("classification") == "blocking_prerequisite"
                    and item.get("active_atom_id_at_creation") == atom_id
                    for item in questions
                ),
                "blocking_questions_as_target": sum(
                    item.get("classification") == "blocking_prerequisite"
                    and item.get("related_atom_id") == atom_id
                    for item in questions
                ),
                "parked_questions": sum(item.get("status") == "parked" for item in atom_questions),
                "evidence_ids": [item.get("id") for item in atom_evidence],
                "question_ids": [item.get("id") for item in atom_questions],
            }
        non_archived = [atom for atom in self.workspace.atoms.values() if atom.get("status") != "archived"]
        mastered = [atom for atom in non_archived if atom.get("status") in {"mastered", "review_due"}]
        skipped = [atom for atom in non_archived if atom.get("status") == "skipped"]
        deferred = [atom for atom in non_archived if atom.get("status") == "deferred"]
        adaptation = self.adaptation_summary()
        return {
            "schema_version": SCHEMA_VERSION,
            "evolution_revision": self.revision,
            "course_revision": self.workspace.revision,
            "generated_at": iso(),
            "course": {
                "total_atoms": len(non_archived),
                "mastered_atoms": len(mastered),
                "mastered_ratio": round(len(mastered) / len(non_archived), 3) if non_archived else 0.0,
                "skipped_atoms": len(skipped),
                "skipped_ratio": round(len(skipped) / len(non_archived), 3) if non_archived else 0.0,
                "deferred_atoms": len(deferred),
                "open_questions": sum(item.get("status") == "open" for item in questions),
                "parked_questions": sum(item.get("status") == "parked" for item in questions),
                "pending_reviews": sum(item.get("status") == "pending" for item in reviews),
                "total_evidence": len(evidence),
            },
            "atoms": atoms,
            "system": {
                "workspace_validation_errors": len(self.workspace.validate()),
                "active_atom_count": sum(atom.get("status") == "active" for atom in self.workspace.atoms.values()),
                "mastered_without_evidence": sum(
                    "without mastered Evidence" in error for error in self.workspace.validate()
                ),
                "raw_messages_stored": False,
                "adaptation_session_count": adaptation["session_count"],
                "active_preference_count": len(adaptation["active_preferences"]),
            },
        }

    def derive_signals(self, metrics: dict[str, Any]) -> list[dict[str, Any]]:
        minimum = int(self.policy.get("bounds", {}).get("minimum_observations", 2))
        signals: list[dict[str, Any]] = []
        for atom_id, atom_metrics in metrics.get("atoms", {}).items():
            observations = unique(atom_metrics.get("evidence_ids", []) + atom_metrics.get("question_ids", []))
            if atom_metrics.get("mastery_failures", 0) >= minimum:
                signals.append(
                    {
                        "type": "teaching_strategy",
                        "target_atom_ids": [atom_id],
                        "observations": observations,
                        "statement": f"Repeated mastery failures suggest targeted remediation for {atom_id}.",
                        "confidence": min(0.95, 0.6 + 0.1 * atom_metrics["mastery_failures"]),
                    }
                )
            if atom_metrics.get("attempts", 0) >= minimum and atom_metrics.get("dimension_spread", 0) >= 0.2:
                signals.append(
                    {
                        "type": "split_atom",
                        "target_atom_ids": [atom_id],
                        "observations": observations,
                        "statement": f"Separated mastery dimensions suggest that {atom_id} may be too broad.",
                        "confidence": min(0.95, 0.65 + atom_metrics["dimension_spread"] / 2),
                    }
                )
            if atom_metrics.get("review_failures", 0) >= 1:
                signals.append(
                    {
                        "type": "adjust_mastery",
                        "target_atom_ids": [atom_id],
                        "observations": observations,
                        "statement": f"Review failure suggests that {atom_id} needs stronger transfer evidence.",
                        "confidence": min(0.95, 0.7 + 0.05 * atom_metrics["review_failures"]),
                    }
                )
        pairs: dict[tuple[str, str], list[str]] = defaultdict(list)
        for question in self.workspace.questions.get("items", []):
            if question.get("classification") != "blocking_prerequisite":
                continue
            source = question.get("related_atom_id")
            target = question.get("active_atom_id_at_creation")
            if source in self.workspace.atoms and target in self.workspace.atoms and source != target:
                pairs[(source, target)].append(question.get("id"))
        for (source, target), question_ids in pairs.items():
            if len(question_ids) < minimum or source in self.workspace.atoms[target].get("prerequisites", []):
                continue
            signals.append(
                {
                    "type": "add_dependency",
                    "target_atom_ids": [source, target],
                    "observations": question_ids,
                    "statement": f"Repeated blocking backtracks suggest dependency {source} -> {target}.",
                    "confidence": min(0.95, 0.65 + 0.1 * len(question_ids)),
                }
            )
        return signals

    def analyze(self, generate_proposals: bool = False) -> dict[str, Any]:
        metrics = self.compute_metrics()
        signals = self.derive_signals(metrics)
        existing = {item.get("fingerprint") for item in self.hypotheses.get("items", [])}
        created_hypotheses: list[str] = []
        created_proposals: list[str] = []
        for signal in signals:
            fingerprint = stable_fingerprint(signal["type"], signal["target_atom_ids"], signal["observations"])
            if fingerprint in existing:
                hypothesis = next(
                    item for item in self.hypotheses["items"] if item.get("fingerprint") == fingerprint
                )
            else:
                hypothesis_id = f"hyp-{len(self.hypotheses.get('items', [])) + 1:06d}"
                hypothesis = {
                    "id": hypothesis_id,
                    "fingerprint": fingerprint,
                    "type": signal["type"],
                    "target_atom_ids": signal["target_atom_ids"],
                    "observations": signal["observations"],
                    "statement": signal["statement"],
                    "confidence": round(float(signal["confidence"]), 3),
                    "status": "open",
                    "created_at": iso(),
                }
                self.hypotheses.setdefault("items", []).append(hypothesis)
                existing.add(fingerprint)
                created_hypotheses.append(hypothesis_id)
            if generate_proposals and not self._has_open_proposal_for_hypothesis(hypothesis["id"]):
                proposal = self.create_proposal(self._proposal_payload_for_signal(signal, hypothesis["id"]), commit=False)
                created_proposals.append(proposal["id"])
        self.metrics = metrics
        self.state["last_analyzed_course_revision"] = self.workspace.revision
        self.state["last_analysis_at"] = metrics["generated_at"]
        self.commit(
            "evolution.analyzed",
            {
                "signals": len(signals),
                "created_hypotheses": created_hypotheses,
                "created_proposals": created_proposals,
            },
        )
        return {
            "metrics": metrics,
            "signals": signals,
            "created_hypothesis_ids": created_hypotheses,
            "created_proposal_ids": created_proposals,
        }

    def _has_open_proposal_for_hypothesis(self, hypothesis_id: str) -> bool:
        return any(
            proposal.get("hypothesis_id") == hypothesis_id
            and proposal.get("status") not in {"rejected", "rolled_back"}
            for proposal in self.proposals()
        )

    def _proposal_payload_for_signal(self, signal: dict[str, Any], hypothesis_id: str) -> dict[str, Any]:
        evolution_type = signal["type"]
        targets = signal["target_atom_ids"]
        if evolution_type == "teaching_strategy":
            change = {
                "atom_id": targets[0],
                "strategy": {
                    "remediation": "target_lowest_dimension",
                    "check_style": "contrast_then_transfer",
                },
            }
        elif evolution_type == "adjust_mastery":
            atom = self.workspace.atoms[targets[0]]
            dimensions = unique(atom.get("mastery", {}).get("required_dimensions", []) + ["transfer"])
            change = {"atom_id": targets[0], "required_dimensions": dimensions}
        elif evolution_type == "add_dependency":
            change = {"from_atom_id": targets[0], "to_atom_id": targets[1]}
        else:
            change = {
                "source_atom_id": targets[0],
                "requires_atom_design": True,
                "recommendation": "Provide a learner-confirmed split proposal with at least two complete Atoms.",
            }
        return {
            "origin": "analysis",
            "scope": "learner",
            "type": evolution_type,
            "target_atom_ids": targets,
            "observations": signal["observations"],
            "hypothesis_id": hypothesis_id,
            "hypothesis": signal["statement"],
            "change": change,
            "evaluation": {"success_criteria": []},
        }

    def create_proposal(self, payload: dict[str, Any], commit: bool = True) -> dict[str, Any]:
        evolution_type = payload.get("type")
        if evolution_type not in EVOLUTION_TYPES:
            raise EvolutionError(f"Invalid evolution type: {evolution_type!r}")
        raw_targets = payload.get("target_atom_ids", [])
        raw_observations = payload.get("observations", [])
        if not isinstance(raw_targets, list) or not all(isinstance(item, str) for item in raw_targets):
            raise EvolutionError("proposal.target_atom_ids must be a string list")
        if not isinstance(raw_observations, list) or not all(
            isinstance(item, str) for item in raw_observations
        ):
            raise EvolutionError("proposal.observations must be a string list")
        observations = unique(raw_observations)
        origin = payload.get("origin", "learner_request" if not observations else "manual")
        if origin not in {"analysis", "learner_request", "manual"}:
            raise EvolutionError("proposal.origin must be analysis, learner_request, or manual")
        proposal_id = f"evo-{proposal_sequence(self.proposal_paths()):06d}"
        proposal = {
            "schema_version": SCHEMA_VERSION,
            "evolution_revision": self.revision,
            "id": proposal_id,
            "base_course_revision": self.workspace.revision,
            "origin": origin,
            "scope": payload.get("scope", "learner"),
            "type": evolution_type,
            "risk": TYPE_RISK[evolution_type],
            "target_atom_ids": unique(raw_targets),
            "observations": observations,
            "hypothesis_id": payload.get("hypothesis_id"),
            "hypothesis": require_string(payload.get("hypothesis"), "proposal.hypothesis"),
            "change": copy.deepcopy(payload.get("change", {})),
            "evaluation": copy.deepcopy(payload.get("evaluation", {"success_criteria": []})),
            "status": "proposed",
            "ready_to_apply": False,
            "approval": None,
            "application": None,
            "monitoring": [],
            "created_at": iso(),
            "updated_at": iso(),
        }
        validation_errors = self.validate_proposal_change(proposal)
        proposal["ready_to_apply"] = not validation_errors and evolution_type != "patch_skill"
        proposal["validation_errors"] = validation_errors
        self.save_proposal(proposal)
        if commit:
            self.commit("evolution.proposed", {"proposal_id": proposal_id, "type": evolution_type})
        return proposal

    def validate_proposal_change(self, proposal: dict[str, Any]) -> list[str]:
        errors: list[str] = []
        evolution_type = proposal.get("type")
        change = proposal.get("change")
        if not isinstance(change, dict):
            return ["change must be a mapping"]
        observations = proposal.get("observations", [])
        if not isinstance(observations, list) or not all(isinstance(item, str) for item in observations):
            errors.append("observations must be a string list")
        else:
            unknown = sorted(set(observations) - self._known_observation_ids())
            if unknown:
                errors.append("unknown observation IDs: " + ", ".join(unknown))
        if not observations and proposal.get("origin") != "learner_request":
            errors.append("a proposal without observations must have origin learner_request")
        errors.extend(self._validate_evaluation(proposal.get("evaluation")))
        for atom_id in proposal.get("target_atom_ids", []):
            if atom_id not in self.workspace.atoms:
                errors.append(f"target Atom does not exist: {atom_id}")
        bounds = self.policy.get("bounds", {})
        if evolution_type == "teaching_strategy":
            atom_id = change.get("atom_id")
            if atom_id not in self.workspace.atoms:
                errors.append("teaching_strategy.change.atom_id must exist")
            if not isinstance(change.get("strategy"), dict) or not change.get("strategy"):
                errors.append("teaching_strategy.change.strategy must be a non-empty mapping")
        elif evolution_type == "adjust_review_intervals":
            intervals = change.get("intervals_days")
            limits = bounds.get("review_interval_days", {"min": 1, "max": 365})
            if not isinstance(intervals, list) or not intervals:
                errors.append("intervals_days must be a non-empty list")
            elif not all(
                isinstance(day, int) and limits["min"] <= day <= limits["max"] for day in intervals
            ):
                errors.append("review intervals exceed policy bounds")
            elif intervals != sorted(set(intervals)):
                errors.append("review intervals must be unique and increasing")
        elif evolution_type == "adjust_mastery":
            atom_id = change.get("atom_id")
            if atom_id not in self.workspace.atoms:
                errors.append("adjust_mastery.change.atom_id must exist")
            dimensions = change.get("required_dimensions")
            if dimensions is not None and (
                not isinstance(dimensions, list) or not dimensions or not all(isinstance(item, str) for item in dimensions)
            ):
                errors.append("required_dimensions must be a non-empty string list")
            for field, policy_name in [
                ("pass_threshold", "mastery_threshold"),
                ("minimum_dimension_score", "minimum_dimension_score"),
            ]:
                if field in change:
                    limit = bounds.get(policy_name, {"min": 0, "max": 1})
                    try:
                        require_number(change[field], field, limit["min"], limit["max"])
                    except AtomLearnError as exc:
                        errors.append(str(exc))
        elif evolution_type in {"add_dependency", "remove_dependency"}:
            source = change.get("from_atom_id")
            target = change.get("to_atom_id")
            if source not in self.workspace.atoms or target not in self.workspace.atoms or source == target:
                errors.append("dependency endpoints must be distinct existing Atoms")
            elif evolution_type == "add_dependency":
                if source in self.workspace.atoms[target].get("prerequisites", []):
                    errors.append("dependency already exists")
                elif self._would_create_cycle(source, target):
                    errors.append("dependency would create a cycle")
            elif source not in self.workspace.atoms[target].get("prerequisites", []):
                errors.append("dependency does not exist")
        elif evolution_type in {"split_atom", "merge_atoms"}:
            restructure = change.get("proposal")
            if not isinstance(restructure, dict):
                errors.append("structural evolution requires change.proposal")
            elif evolution_type == "split_atom" and restructure.get("action") != "split":
                errors.append("split_atom requires a split restructure proposal")
            elif evolution_type == "merge_atoms" and restructure.get("action") != "merge":
                errors.append("merge_atoms requires a merge restructure proposal")
        elif evolution_type == "patch_skill":
            if not change.get("summary"):
                errors.append("patch_skill requires a candidate summary")
        return unique(errors)

    def _known_observation_ids(self) -> set[str]:
        identifiers = {
            item.get("id")
            for collection in [self.workspace.evidence, self.workspace.questions, self.workspace.reviews]
            for item in collection.get("items", [])
            if isinstance(item, dict) and isinstance(item.get("id"), str)
        }
        events_path = self.workspace.meta / "events.ndjson"
        if events_path.is_file():
            for line in events_path.read_text(encoding="utf-8").splitlines():
                try:
                    event = json.loads(line)
                except json.JSONDecodeError:
                    continue
                if isinstance(event, dict) and isinstance(event.get("event_id"), str):
                    identifiers.add(event["event_id"])
        return identifiers

    def _validate_evaluation(self, evaluation: Any) -> list[str]:
        if not isinstance(evaluation, dict):
            return ["evaluation must be a mapping"]
        criteria = evaluation.get("success_criteria", [])
        if not isinstance(criteria, list):
            return ["evaluation.success_criteria must be a list"]
        errors: list[str] = []
        for index, criterion in enumerate(criteria):
            label = f"evaluation.success_criteria[{index}]"
            if not isinstance(criterion, dict):
                errors.append(f"{label} must be a mapping")
                continue
            metric = criterion.get("metric")
            if metric not in SUPPORTED_METRICS:
                errors.append(f"{label}.metric is unsupported: {metric!r}")
            atom_id = criterion.get("atom_id")
            if isinstance(metric, str) and metric.startswith("atom."):
                if atom_id not in self.workspace.atoms:
                    errors.append(f"{label}.atom_id must name an existing Atom")
            elif atom_id is not None:
                errors.append(f"{label}.atom_id is only valid for atom metrics")
            operator = criterion.get("operator", "gte")
            if operator not in SUPPORTED_OPERATORS:
                errors.append(f"{label}.operator is unsupported: {operator!r}")
            value = criterion.get("value")
            if not isinstance(value, (int, float)) or isinstance(value, bool):
                errors.append(f"{label}.value must be numeric")
            minimum = criterion.get("min_observations", 1)
            if not isinstance(minimum, int) or isinstance(minimum, bool) or minimum < 1:
                errors.append(f"{label}.min_observations must be a positive integer")
        return errors

    def _would_create_cycle(self, source: str, target: str) -> bool:
        successors: dict[str, list[str]] = defaultdict(list)
        for atom_id, atom in self.workspace.atoms.items():
            for prerequisite in atom.get("prerequisites", []):
                successors[prerequisite].append(atom_id)
        stack = [target]
        visited: set[str] = set()
        while stack:
            node = stack.pop()
            if node == source:
                return True
            if node in visited:
                continue
            visited.add(node)
            stack.extend(successors[node])
        return False

    def preview(self, proposal_id: str) -> dict[str, Any]:
        proposal = self.find_proposal(proposal_id)
        errors = self.validate_proposal_change(proposal)
        return {
            "proposal_id": proposal_id,
            "type": proposal["type"],
            "risk": proposal["risk"],
            "status": proposal["status"],
            "base_course_revision": proposal["base_course_revision"],
            "current_course_revision": self.workspace.revision,
            "stale": proposal["base_course_revision"] != self.workspace.revision,
            "ready_to_apply": not errors and proposal["type"] != "patch_skill",
            "validation_errors": errors,
            "change": proposal["change"],
            "protected_invariants": self.policy.get("protected_invariants", []),
        }

    def approve(self, proposal_id: str, authority: str, actor: str) -> dict[str, Any]:
        proposal = self.find_proposal(proposal_id)
        if proposal.get("status") != "proposed":
            raise EvolutionError(f"Proposal {proposal_id} cannot be approved from {proposal.get('status')}")
        errors = self.validate_proposal_change(proposal)
        if errors:
            raise EvolutionError("Proposal is not ready:\n- " + "\n- ".join(errors))
        required = self.policy.get("risk_permissions", {}).get(proposal["risk"], RISK_AUTHORITY[proposal["risk"]])
        if authority not in AUTHORITY_RANK or AUTHORITY_RANK[authority] < AUTHORITY_RANK[required]:
            raise EvolutionError(f"{proposal['risk']} risk requires {required} authority")
        proposal["status"] = "approved"
        proposal["approval"] = {
            "authority": authority,
            "actor": require_string(actor, "approval actor"),
            "at": iso(),
        }
        self.save_proposal(proposal)
        self.commit("evolution.approved", {"proposal_id": proposal_id, "authority": authority})
        return proposal

    def reject(self, proposal_id: str, reason: str) -> dict[str, Any]:
        proposal = self.find_proposal(proposal_id)
        if proposal.get("status") not in {"proposed", "approved"}:
            raise EvolutionError(f"Proposal {proposal_id} cannot be rejected from {proposal.get('status')}")
        proposal["status"] = "rejected"
        proposal["rejection"] = {"reason": require_string(reason, "rejection reason"), "at": iso()}
        self.save_proposal(proposal)
        self.commit("evolution.rejected", {"proposal_id": proposal_id})
        return proposal

    def create_checkpoint(self, proposal: dict[str, Any]) -> Path:
        checkpoint = {
            "schema_version": SCHEMA_VERSION,
            "proposal_id": proposal["id"],
            "created_at": iso(),
            "course_revision": self.workspace.revision,
            "workspace": {
                "course": copy.deepcopy(self.workspace.course),
                "graph": copy.deepcopy(self.workspace.graph),
                "atoms": copy.deepcopy(self.workspace.atoms),
                "question_links": {
                    item["id"]: {
                        "related_atom_id": item.get("related_atom_id"),
                        "status": item.get("status"),
                        "migrated_from_atom_id": item.get("migrated_from_atom_id"),
                    }
                    for item in self.workspace.questions.get("items", [])
                },
                "review_links": {
                    item["id"]: {
                        "status": item.get("status"),
                        "superseded_by_atom_id": item.get("superseded_by_atom_id"),
                        "superseded_at": item.get("superseded_at"),
                    }
                    for item in self.workspace.reviews.get("items", [])
                },
            },
            "evolution_policy": copy.deepcopy(self.policy),
        }
        path = self.root / "checkpoints" / f"{proposal['id']}-before.yaml"
        write_yaml(path, checkpoint)
        return path

    def apply(self, proposal_id: str) -> dict[str, Any]:
        proposal = self.find_proposal(proposal_id)
        if proposal.get("status") != "approved":
            raise EvolutionError(f"Proposal {proposal_id} must be approved before application")
        if proposal.get("type") == "patch_skill":
            raise EvolutionError("Runtime Skill patches are forbidden; create a reviewed repository patch instead")
        if proposal.get("base_course_revision") != self.workspace.revision:
            raise EvolutionError(
                f"Proposal is stale: based on course revision {proposal.get('base_course_revision')}, "
                f"current is {self.workspace.revision}"
            )
        errors = self.validate_proposal_change(proposal)
        if errors:
            raise EvolutionError("Proposal failed pre-application validation:\n- " + "\n- ".join(errors))
        checkpoint = self.create_checkpoint(proposal)
        baseline = self.compute_metrics()
        evolution_type = proposal["type"]
        change = proposal["change"]
        course_changed = evolution_type in COURSE_MUTATION_TYPES
        try:
            if evolution_type == "teaching_strategy":
                atom_id = change["atom_id"]
                self.policy.setdefault("learner_strategy", {}).setdefault("atoms", {})[atom_id] = copy.deepcopy(
                    change["strategy"]
                )
            elif evolution_type == "adjust_review_intervals":
                self.workspace.course.setdefault("settings", {})["review_intervals_days"] = list(
                    change["intervals_days"]
                )
            elif evolution_type == "adjust_mastery":
                atom = self.workspace.atoms[change["atom_id"]]
                mastery = atom.setdefault("mastery", {})
                for field in ["required_dimensions", "pass_threshold", "minimum_dimension_score"]:
                    if field in change:
                        mastery[field] = copy.deepcopy(change[field])
                if atom.get("status") in {"mastered", "review_due"}:
                    atom["status"] = "available"
                    atom["evolution_revalidation_required"] = proposal_id
            elif evolution_type in {"add_dependency", "remove_dependency"}:
                target = self.workspace.atoms[change["to_atom_id"]]
                prerequisites = list(target.get("prerequisites", []))
                if evolution_type == "add_dependency":
                    prerequisites.append(change["from_atom_id"])
                    if (
                        target.get("status") in {"mastered", "review_due"}
                        and self.workspace.atoms[change["from_atom_id"]].get("status")
                        not in {"mastered", "review_due"}
                    ):
                        target["status"] = "available"
                        target["evolution_revalidation_required"] = proposal_id
                else:
                    prerequisites = [item for item in prerequisites if item != change["from_atom_id"]]
                target["prerequisites"] = unique(prerequisites)
                self.workspace.rebuild_graph()
            elif evolution_type in {"split_atom", "merge_atoms"}:
                self.workspace.restructure(copy.deepcopy(change["proposal"]))
            if course_changed:
                self.workspace.commit(
                    "evolution.applied",
                    f"Applied approved evolution proposal {proposal_id}",
                    {"proposal_id": proposal_id, "type": evolution_type},
                )
        except (AtomLearnError, KeyError, TypeError, ValueError) as exc:
            proposal["status"] = "blocked"
            proposal["application_error"] = str(exc)
            self.save_proposal(proposal)
            self.commit("evolution.application_blocked", {"proposal_id": proposal_id, "error": str(exc)})
            raise EvolutionError(f"Application was blocked: {exc}") from exc
        proposal["status"] = "applied"
        proposal["application"] = {
            "at": iso(),
            "checkpoint": str(checkpoint.relative_to(self.workspace.root)),
            "course_changed": course_changed,
            "applied_course_revision": self.workspace.revision,
            "baseline_metrics": baseline,
        }
        self.save_proposal(proposal)
        self.commit("evolution.applied", {"proposal_id": proposal_id, "type": evolution_type})
        return proposal

    def monitor(self, proposal_id: str) -> dict[str, Any]:
        proposal = self.find_proposal(proposal_id)
        if proposal.get("status") not in {"applied", "monitoring", "promoted"}:
            raise EvolutionError(f"Proposal {proposal_id} is not in a monitorable state")
        evaluation_errors = self._validate_evaluation(proposal.get("evaluation"))
        if evaluation_errors:
            raise EvolutionError("Proposal evaluation is invalid:\n- " + "\n- ".join(evaluation_errors))
        current = self.compute_metrics()
        criteria = proposal.get("evaluation", {}).get("success_criteria", [])
        results = [self._evaluate_criterion(criterion, current) for criterion in criteria]
        evaluated = bool(results) and all(result["status"] != "insufficient" for result in results)
        passed = evaluated and all(result["passed"] for result in results)
        outcome = "passed" if passed else "failed" if evaluated else "insufficient"
        record = {
            "at": iso(),
            "course_revision": self.workspace.revision,
            "outcome": outcome,
            "criteria": results,
        }
        proposal.setdefault("monitoring", []).append(record)
        proposal["status"] = "promoted" if passed else "monitoring"
        self.metrics = current
        experiment = {
            "schema_version": SCHEMA_VERSION,
            "proposal_id": proposal_id,
            "baseline_metrics": proposal.get("application", {}).get("baseline_metrics", {}),
            "current_metrics": current,
            "result": record,
        }
        write_yaml(self.root / "experiments" / f"{proposal_id}-{len(proposal['monitoring']):03d}.yaml", experiment)
        self.save_proposal(proposal)
        self.commit("evolution.monitored", {"proposal_id": proposal_id, "outcome": outcome})
        return record

    def _evaluate_criterion(self, criterion: dict[str, Any], metrics: dict[str, Any]) -> dict[str, Any]:
        metric = criterion.get("metric")
        atom_id = criterion.get("atom_id")
        minimum_observations = int(criterion.get("min_observations", 1))
        if atom_id:
            atom_metrics = metrics.get("atoms", {}).get(atom_id)
            if not atom_metrics or atom_metrics.get("evidence_count", 0) < minimum_observations:
                return {"criterion": criterion, "status": "insufficient", "passed": False, "actual": None}
            field = metric.removeprefix("atom.") if isinstance(metric, str) else ""
            actual = atom_metrics.get(field)
        elif isinstance(metric, str) and metric.startswith("course."):
            actual = metrics.get("course", {}).get(metric.removeprefix("course."))
        elif isinstance(metric, str) and metric.startswith("system."):
            actual = metrics.get("system", {}).get(metric.removeprefix("system."))
        else:
            actual = None
        if actual is None:
            return {"criterion": criterion, "status": "insufficient", "passed": False, "actual": None}
        operator = criterion.get("operator", "gte")
        target = criterion.get("value")
        operations = {
            "gte": lambda a, b: a >= b,
            "lte": lambda a, b: a <= b,
            "gt": lambda a, b: a > b,
            "lt": lambda a, b: a < b,
            "eq": lambda a, b: a == b,
        }
        if operator not in operations or not isinstance(target, (int, float)) or isinstance(target, bool):
            return {"criterion": criterion, "status": "invalid", "passed": False, "actual": actual}
        return {
            "criterion": criterion,
            "status": "evaluated",
            "passed": bool(operations[operator](actual, target)),
            "actual": actual,
        }

    def rollback(self, proposal_id: str, reason: str) -> dict[str, Any]:
        proposal = self.find_proposal(proposal_id)
        if proposal.get("status") not in {"applied", "monitoring", "promoted"}:
            raise EvolutionError(f"Proposal {proposal_id} cannot be rolled back from {proposal.get('status')}")
        application = proposal.get("application") or {}
        expected_checkpoint = (self.root / "checkpoints" / f"{proposal_id}-before.yaml").resolve()
        checkpoint_reference = application.get("checkpoint")
        if not isinstance(checkpoint_reference, str) or (
            self.workspace.root / checkpoint_reference
        ).resolve() != expected_checkpoint:
            raise EvolutionError("Proposal checkpoint reference is invalid")
        checkpoint_path = expected_checkpoint
        if not checkpoint_path.is_file():
            raise EvolutionError(f"Checkpoint not found: {checkpoint_path}")
        checkpoint = read_data(checkpoint_path)
        if application.get("course_changed"):
            applied_revision = application.get("applied_course_revision")
            if self.workspace.revision != applied_revision:
                raise EvolutionError(
                    "Automatic rollback is unsafe because learning state changed after application; "
                    "create a manual migration proposal instead"
                )
            current_revision = self.workspace.revision
            current_atoms = copy.deepcopy(self.workspace.atoms)
            snapshot = checkpoint["workspace"]
            self.workspace.course = copy.deepcopy(snapshot["course"])
            self.workspace.graph = copy.deepcopy(snapshot["graph"])
            self.workspace.atoms = copy.deepcopy(snapshot["atoms"])
            for question in self.workspace.questions.get("items", []):
                saved = snapshot.get("question_links", {}).get(question.get("id"))
                if saved:
                    question.update(copy.deepcopy(saved))
            for review in self.workspace.reviews.get("items", []):
                saved = snapshot.get("review_links", {}).get(review.get("id"))
                if saved:
                    review.update(copy.deepcopy(saved))
            for atom_id, atom in current_atoms.items():
                if atom_id not in self.workspace.atoms:
                    archived = copy.deepcopy(atom)
                    archived["status"] = "archived"
                    archived["archived_reason"] = f"rollback of {proposal_id}"
                    archived["prerequisites"] = []
                    self.workspace.atoms[atom_id] = archived
            self.workspace.course["revision"] = current_revision
            for record in [
                self.workspace.graph,
                self.workspace.current,
                self.workspace.questions,
                self.workspace.evidence,
                self.workspace.reviews,
            ]:
                record["revision"] = current_revision
            for atom in self.workspace.atoms.values():
                atom["revision"] = current_revision
            self.workspace.rebuild_graph()
            self.workspace.commit(
                "evolution.rolled_back",
                require_string(reason, "rollback reason"),
                {"proposal_id": proposal_id},
            )
        self.policy = copy.deepcopy(checkpoint["evolution_policy"])
        proposal["status"] = "rolled_back"
        proposal["rollback"] = {
            "at": iso(),
            "reason": require_string(reason, "rollback reason"),
            "course_revision": self.workspace.revision,
        }
        self.save_proposal(proposal)
        self.commit("evolution.rolled_back", {"proposal_id": proposal_id})
        return proposal

    def status_summary(self) -> dict[str, Any]:
        proposals = self.proposals()
        validation_errors = self.validate()
        by_status: dict[str, int] = defaultdict(int)
        for proposal in proposals:
            by_status[proposal.get("status", "unknown")] += 1
        return {
            "valid": not validation_errors,
            "validation_errors": validation_errors,
            "evolution_revision": self.revision,
            "course_revision": self.workspace.revision,
            "mode": self.policy.get("mode"),
            "last_analysis_at": self.state.get("last_analysis_at"),
            "open_hypotheses": sum(item.get("status") == "open" for item in self.hypotheses.get("items", [])),
            "proposals": dict(sorted(by_status.items())),
            "learner_strategy": self.policy.get("learner_strategy", {}),
            "session_adaptation": self.adaptation_summary(),
        }

    def render(self) -> None:
        proposals = self.proposals()
        lines = [
            "# Evolution State",
            "",
            "> Generated by AtomLearn Evolution Engine. Use `atomlearn evolve` commands to change state.",
            "",
            "## Policy",
            "",
            f"- Mode: `{self.policy.get('mode')}`",
            f"- Evolution revision: {self.revision}",
            f"- Course revision: {self.workspace.revision}",
            "- Runtime Skill patching: forbidden",
            "",
            "## Open Hypotheses",
            "",
        ]
        open_hypotheses = [item for item in self.hypotheses.get("items", []) if item.get("status") == "open"]
        lines.extend(
            [f"- `{item['id']}` [{item['type']}] {item['statement']}" for item in open_hypotheses]
            or ["- None"]
        )
        lines.extend(["", "## Proposals", ""])
        lines.extend(
            [
                f"- `{item['id']}` [{item['risk']}/{item['status']}] {item['type']} — {item['hypothesis']}"
                for item in proposals
            ]
            or ["- None"]
        )
        adaptation = self.adaptation_summary()
        lines.extend(["", "## Session Adaptation", ""])
        if adaptation["enabled"]:
            lines.extend(
                [
                    f"- Adaptation revision: `{adaptation['adaptation_revision']}`",
                    f"- Observed sessions: `{adaptation['session_count']}`",
                    f"- Pending preferences: `{adaptation['pending_preferences']}`",
                ]
            )
            lines.extend(
                [f"- `{dimension}` = `{value}`" for dimension, value in adaptation["active_preferences"].items()]
                or ["- Active preferences: none"]
            )
        else:
            lines.append("- Not initialized")
        lines.extend(["", "## Last Analysis", "", str(self.state.get("last_analysis_at") or "Not analyzed"), ""])
        atomic_text(self.workspace.root / "EVOLUTION.md", "\n".join(lines).rstrip() + "\n")


def add_revision_argument(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--expected-evolution-revision", type=int)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Analyze and safely evolve an AtomLearn workspace")
    sub = parser.add_subparsers(dest="action", required=True)
    simple_help = {
        "status": "Show evolution policy, revisions, proposals, and monitoring status",
        "validate": "Validate evolution policy, proposals, snapshots, and audit history",
        "list": "List proposals with an optional status filter",
        "policy": "Show the effective bounded self-evolution policy",
    }
    for action in ["status", "validate", "list", "policy"]:
        action_parser = sub.add_parser(action, help=simple_help[action])
        action_parser.add_argument("workspace")
        if action == "list":
            action_parser.add_argument("--status")
        if action in {"status", "policy"}:
            action_parser.add_argument("--json", action="store_true")
    analyze = sub.add_parser("analyze", help="Analyze Evidence and optionally draft bounded proposals")
    analyze.add_argument("workspace")
    analyze.add_argument("--propose", action="store_true")
    add_revision_argument(analyze)
    propose = sub.add_parser("propose", help="Create a policy-checked evolution proposal")
    propose.add_argument("workspace")
    propose.add_argument("--input", required=True)
    add_revision_argument(propose)
    preview = sub.add_parser("preview", help="Preview proposal effects without mutating course state")
    preview.add_argument("workspace")
    preview.add_argument("proposal_id")
    approve = sub.add_parser("approve", help="Approve a proposal with explicit authority and actor")
    approve.add_argument("workspace")
    approve.add_argument("proposal_id")
    approve.add_argument("--authority", choices=sorted(AUTHORITY_RANK), required=True)
    approve.add_argument("--actor", required=True)
    add_revision_argument(approve)
    reject = sub.add_parser("reject", help="Reject a proposal with an auditable reason")
    reject.add_argument("workspace")
    reject.add_argument("proposal_id")
    reject.add_argument("--reason", required=True)
    add_revision_argument(reject)
    apply_parser = sub.add_parser("apply", help="Apply an approved proposal and create a rollback snapshot")
    apply_parser.add_argument("workspace")
    apply_parser.add_argument("proposal_id")
    add_revision_argument(apply_parser)
    monitor = sub.add_parser("monitor", help="Evaluate an applied proposal against its success criteria")
    monitor.add_argument("workspace")
    monitor.add_argument("proposal_id")
    add_revision_argument(monitor)
    rollback = sub.add_parser("rollback", help="Roll back an applied proposal to its recovery snapshot")
    rollback.add_argument("workspace")
    rollback.add_argument("proposal_id")
    rollback.add_argument("--reason", required=True)
    add_revision_argument(rollback)
    capsule = sub.add_parser("capsule", help="Build lint preview export or ingest privacy-minimized Capsules", add_help=False)
    capsule.add_argument("-h", "--help", action="store_true", dest="capsule_help")
    capsule.add_argument("capsule_args", nargs=argparse.REMAINDER)
    return parser


def run(argv: list[str] | None = None) -> None:
    args = build_parser().parse_args(argv)
    if args.action == "capsule":
        from capsule import CapsuleError, run as run_capsule

        try:
            run_capsule(["--help"] if args.capsule_help else args.capsule_args)
        except (CapsuleError, PlatformStateError, OSError, json.JSONDecodeError, yaml.YAMLError) as exc:
            raise EvolutionError(str(exc)) from exc
        return
    engine = EvolutionEngine.load(args.workspace)
    if args.action != "validate":
        existing_errors = engine.validate()
        if existing_errors:
            raise EvolutionError(
                "Refusing to use invalid evolution state; run evolve validate and repair it first:\n- "
                + "\n- ".join(existing_errors)
            )
    if args.action == "status":
        print(json.dumps(engine.status_summary(), ensure_ascii=False, indent=2))
        return
    if args.action == "validate":
        errors = engine.validate()
        if errors:
            raise EvolutionError("Evolution validation failed:\n- " + "\n- ".join(errors))
        print(json.dumps({"ok": True, "evolution_revision": engine.revision}, indent=2))
        return
    if args.action == "list":
        proposals = engine.proposals()
        if args.status:
            proposals = [item for item in proposals if item.get("status") == args.status]
        print(json.dumps(proposals, ensure_ascii=False, indent=2))
        return
    if args.action == "policy":
        print(json.dumps(engine.policy, ensure_ascii=False, indent=2))
        return
    if args.action == "preview":
        print(json.dumps(engine.preview(args.proposal_id), ensure_ascii=False, indent=2))
        return
    engine.expect_revision(args.expected_evolution_revision)
    if args.action == "analyze":
        result = engine.analyze(args.propose)
    elif args.action == "propose":
        result = engine.create_proposal(read_data(Path(args.input)))
    elif args.action == "approve":
        result = engine.approve(args.proposal_id, args.authority, args.actor)
    elif args.action == "reject":
        result = engine.reject(args.proposal_id, args.reason)
    elif args.action == "apply":
        result = engine.apply(args.proposal_id)
    elif args.action == "monitor":
        result = engine.monitor(args.proposal_id)
    elif args.action == "rollback":
        result = engine.rollback(args.proposal_id, args.reason)
    else:  # pragma: no cover
        raise EvolutionError(f"Unhandled evolution action: {args.action}")
    output = {
        "ok": True,
        "evolution_revision": engine.revision,
        "course_revision": engine.workspace.revision,
        "result": result,
    }
    print(json.dumps(output, ensure_ascii=False, indent=2))


def main(argv: list[str] | None = None) -> int:
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8")
    if hasattr(sys.stderr, "reconfigure"):
        sys.stderr.reconfigure(encoding="utf-8")
    try:
        run(argv)
        return 0
    except (EvolutionError, AtomLearnError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
